name: test
on:
  push:
    branches:
      - main

jobs:
  test:
    name: Runs tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Run make test
        run: make test
